// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmrfdsccggznmdrefzeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttcmZkc2NjZ2d6bm1kcmVmemVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzc1MzMsImV4cCI6MjA2ODg1MzUzM30.JRwkW8ifQdDp1x4pQzMGqjeoZHcFiy6p4qo8E8S-87U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});